/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormulariosRouteImport } from './routes/formularios'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ActivarCuentaRouteImport } from './routes/activar-cuenta'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as FormulariosIndexRouteImport } from './routes/formularios.index'
import { Route as AcademiaIndexRouteImport } from './routes/academia.index'
import { Route as PortalSuscripcionesRouteImport } from './routes/portal.suscripciones'
import { Route as PortalRecursosClinicosRouteImport } from './routes/portal.recursos-clinicos'
import { Route as PortalPlanRouteImport } from './routes/portal.plan'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalFormularioRouteImport } from './routes/portal.formulario'
import { Route as FormulariosNuevaRouteImport } from './routes/formularios.nueva'
import { Route as AcademiaRecursosRouteImport } from './routes/academia.recursos'
import { Route as AcademiaExplorarRouteImport } from './routes/academia.explorar'
import { Route as AcademiaDirectoRouteImport } from './routes/academia.directo'
import { Route as AcademiaAlumnosRouteImport } from './routes/academia.alumnos'
import { Route as AcademiaCursoCourseIdRouteImport } from './routes/academia.curso.$courseId'
import { Route as AcademiaLeccionCourseIdLessonIdRouteImport } from './routes/academia.leccion.$courseId.$lessonId'

const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosRoute = FormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarCuentaRoute = ActivarCuentaRouteImport.update({
  id: '/activar-cuenta',
  path: '/activar-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosIndexRoute = FormulariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormulariosRoute,
} as any)
const AcademiaIndexRoute = AcademiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademiaRoute,
} as any)
const PortalSuscripcionesRoute = PortalSuscripcionesRouteImport.update({
  id: '/portal/suscripciones',
  path: '/portal/suscripciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRecursosClinicosRoute = PortalRecursosClinicosRouteImport.update({
  id: '/portal/recursos-clinicos',
  path: '/portal/recursos-clinicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPlanRoute = PortalPlanRouteImport.update({
  id: '/portal/plan',
  path: '/portal/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/portal/perfil',
  path: '/portal/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFormularioRoute = PortalFormularioRouteImport.update({
  id: '/portal/formulario',
  path: '/portal/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosNuevaRoute = FormulariosNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => FormulariosRoute,
} as any)
const AcademiaRecursosRoute = AcademiaRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AcademiaRoute,
} as any)
const AcademiaExplorarRoute = AcademiaExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AcademiaRoute,
} as any)
const AcademiaDirectoRoute = AcademiaDirectoRouteImport.update({
  id: '/directo',
  path: '/directo',
  getParentRoute: () => AcademiaRoute,
} as any)
const AcademiaAlumnosRoute = AcademiaAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AcademiaRoute,
} as any)
const AcademiaCursoCourseIdRoute = AcademiaCursoCourseIdRouteImport.update({
  id: '/curso/$courseId',
  path: '/curso/$courseId',
  getParentRoute: () => AcademiaRoute,
} as any)
const AcademiaLeccionCourseIdLessonIdRoute =
  AcademiaLeccionCourseIdLessonIdRouteImport.update({
    id: '/leccion/$courseId/$lessonId',
    path: '/leccion/$courseId/$lessonId',
    getParentRoute: () => AcademiaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRouteWithChildren
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/ajustes': typeof AjustesRoute
  '/calendario': typeof CalendarioRoute
  '/formularios': typeof FormulariosRouteWithChildren
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/recursos': typeof RecursosRoute
  '/academia/alumnos': typeof AcademiaAlumnosRoute
  '/academia/directo': typeof AcademiaDirectoRoute
  '/academia/explorar': typeof AcademiaExplorarRoute
  '/academia/recursos': typeof AcademiaRecursosRoute
  '/formularios/nueva': typeof FormulariosNuevaRoute
  '/portal/formulario': typeof PortalFormularioRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/plan': typeof PortalPlanRoute
  '/portal/recursos-clinicos': typeof PortalRecursosClinicosRoute
  '/portal/suscripciones': typeof PortalSuscripcionesRoute
  '/academia/': typeof AcademiaIndexRoute
  '/formularios/': typeof FormulariosIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/academia/curso/$courseId': typeof AcademiaCursoCourseIdRoute
  '/academia/leccion/$courseId/$lessonId': typeof AcademiaLeccionCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/ajustes': typeof AjustesRoute
  '/calendario': typeof CalendarioRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/recursos': typeof RecursosRoute
  '/academia/alumnos': typeof AcademiaAlumnosRoute
  '/academia/directo': typeof AcademiaDirectoRoute
  '/academia/explorar': typeof AcademiaExplorarRoute
  '/academia/recursos': typeof AcademiaRecursosRoute
  '/formularios/nueva': typeof FormulariosNuevaRoute
  '/portal/formulario': typeof PortalFormularioRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/plan': typeof PortalPlanRoute
  '/portal/recursos-clinicos': typeof PortalRecursosClinicosRoute
  '/portal/suscripciones': typeof PortalSuscripcionesRoute
  '/academia': typeof AcademiaIndexRoute
  '/formularios': typeof FormulariosIndexRoute
  '/portal': typeof PortalIndexRoute
  '/academia/curso/$courseId': typeof AcademiaCursoCourseIdRoute
  '/academia/leccion/$courseId/$lessonId': typeof AcademiaLeccionCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRouteWithChildren
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/ajustes': typeof AjustesRoute
  '/calendario': typeof CalendarioRoute
  '/formularios': typeof FormulariosRouteWithChildren
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/recursos': typeof RecursosRoute
  '/academia/alumnos': typeof AcademiaAlumnosRoute
  '/academia/directo': typeof AcademiaDirectoRoute
  '/academia/explorar': typeof AcademiaExplorarRoute
  '/academia/recursos': typeof AcademiaRecursosRoute
  '/formularios/nueva': typeof FormulariosNuevaRoute
  '/portal/formulario': typeof PortalFormularioRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/plan': typeof PortalPlanRoute
  '/portal/recursos-clinicos': typeof PortalRecursosClinicosRoute
  '/portal/suscripciones': typeof PortalSuscripcionesRoute
  '/academia/': typeof AcademiaIndexRoute
  '/formularios/': typeof FormulariosIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/academia/curso/$courseId': typeof AcademiaCursoCourseIdRoute
  '/academia/leccion/$courseId/$lessonId': typeof AcademiaLeccionCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/activar-cuenta'
    | '/ajustes'
    | '/calendario'
    | '/formularios'
    | '/login'
    | '/pacientes'
    | '/recuperar-password'
    | '/recursos'
    | '/academia/alumnos'
    | '/academia/directo'
    | '/academia/explorar'
    | '/academia/recursos'
    | '/formularios/nueva'
    | '/portal/formulario'
    | '/portal/perfil'
    | '/portal/plan'
    | '/portal/recursos-clinicos'
    | '/portal/suscripciones'
    | '/academia/'
    | '/formularios/'
    | '/portal/'
    | '/academia/curso/$courseId'
    | '/academia/leccion/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activar-cuenta'
    | '/ajustes'
    | '/calendario'
    | '/login'
    | '/pacientes'
    | '/recuperar-password'
    | '/recursos'
    | '/academia/alumnos'
    | '/academia/directo'
    | '/academia/explorar'
    | '/academia/recursos'
    | '/formularios/nueva'
    | '/portal/formulario'
    | '/portal/perfil'
    | '/portal/plan'
    | '/portal/recursos-clinicos'
    | '/portal/suscripciones'
    | '/academia'
    | '/formularios'
    | '/portal'
    | '/academia/curso/$courseId'
    | '/academia/leccion/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/activar-cuenta'
    | '/ajustes'
    | '/calendario'
    | '/formularios'
    | '/login'
    | '/pacientes'
    | '/recuperar-password'
    | '/recursos'
    | '/academia/alumnos'
    | '/academia/directo'
    | '/academia/explorar'
    | '/academia/recursos'
    | '/formularios/nueva'
    | '/portal/formulario'
    | '/portal/perfil'
    | '/portal/plan'
    | '/portal/recursos-clinicos'
    | '/portal/suscripciones'
    | '/academia/'
    | '/formularios/'
    | '/portal/'
    | '/academia/curso/$courseId'
    | '/academia/leccion/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRouteWithChildren
  ActivarCuentaRoute: typeof ActivarCuentaRoute
  AjustesRoute: typeof AjustesRoute
  CalendarioRoute: typeof CalendarioRoute
  FormulariosRoute: typeof FormulariosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
  RecursosRoute: typeof RecursosRoute
  PortalFormularioRoute: typeof PortalFormularioRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  PortalPlanRoute: typeof PortalPlanRoute
  PortalRecursosClinicosRoute: typeof PortalRecursosClinicosRoute
  PortalSuscripcionesRoute: typeof PortalSuscripcionesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios': {
      id: '/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof FormulariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar-cuenta': {
      id: '/activar-cuenta'
      path: '/activar-cuenta'
      fullPath: '/activar-cuenta'
      preLoaderRoute: typeof ActivarCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios/': {
      id: '/formularios/'
      path: '/'
      fullPath: '/formularios/'
      preLoaderRoute: typeof FormulariosIndexRouteImport
      parentRoute: typeof FormulariosRoute
    }
    '/academia/': {
      id: '/academia/'
      path: '/'
      fullPath: '/academia/'
      preLoaderRoute: typeof AcademiaIndexRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/portal/suscripciones': {
      id: '/portal/suscripciones'
      path: '/portal/suscripciones'
      fullPath: '/portal/suscripciones'
      preLoaderRoute: typeof PortalSuscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/recursos-clinicos': {
      id: '/portal/recursos-clinicos'
      path: '/portal/recursos-clinicos'
      fullPath: '/portal/recursos-clinicos'
      preLoaderRoute: typeof PortalRecursosClinicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/plan': {
      id: '/portal/plan'
      path: '/portal/plan'
      fullPath: '/portal/plan'
      preLoaderRoute: typeof PortalPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/portal/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/formulario': {
      id: '/portal/formulario'
      path: '/portal/formulario'
      fullPath: '/portal/formulario'
      preLoaderRoute: typeof PortalFormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios/nueva': {
      id: '/formularios/nueva'
      path: '/nueva'
      fullPath: '/formularios/nueva'
      preLoaderRoute: typeof FormulariosNuevaRouteImport
      parentRoute: typeof FormulariosRoute
    }
    '/academia/recursos': {
      id: '/academia/recursos'
      path: '/recursos'
      fullPath: '/academia/recursos'
      preLoaderRoute: typeof AcademiaRecursosRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/academia/explorar': {
      id: '/academia/explorar'
      path: '/explorar'
      fullPath: '/academia/explorar'
      preLoaderRoute: typeof AcademiaExplorarRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/academia/directo': {
      id: '/academia/directo'
      path: '/directo'
      fullPath: '/academia/directo'
      preLoaderRoute: typeof AcademiaDirectoRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/academia/alumnos': {
      id: '/academia/alumnos'
      path: '/alumnos'
      fullPath: '/academia/alumnos'
      preLoaderRoute: typeof AcademiaAlumnosRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/academia/curso/$courseId': {
      id: '/academia/curso/$courseId'
      path: '/curso/$courseId'
      fullPath: '/academia/curso/$courseId'
      preLoaderRoute: typeof AcademiaCursoCourseIdRouteImport
      parentRoute: typeof AcademiaRoute
    }
    '/academia/leccion/$courseId/$lessonId': {
      id: '/academia/leccion/$courseId/$lessonId'
      path: '/leccion/$courseId/$lessonId'
      fullPath: '/academia/leccion/$courseId/$lessonId'
      preLoaderRoute: typeof AcademiaLeccionCourseIdLessonIdRouteImport
      parentRoute: typeof AcademiaRoute
    }
  }
}

interface AcademiaRouteChildren {
  AcademiaAlumnosRoute: typeof AcademiaAlumnosRoute
  AcademiaDirectoRoute: typeof AcademiaDirectoRoute
  AcademiaExplorarRoute: typeof AcademiaExplorarRoute
  AcademiaRecursosRoute: typeof AcademiaRecursosRoute
  AcademiaIndexRoute: typeof AcademiaIndexRoute
  AcademiaCursoCourseIdRoute: typeof AcademiaCursoCourseIdRoute
  AcademiaLeccionCourseIdLessonIdRoute: typeof AcademiaLeccionCourseIdLessonIdRoute
}

const AcademiaRouteChildren: AcademiaRouteChildren = {
  AcademiaAlumnosRoute: AcademiaAlumnosRoute,
  AcademiaDirectoRoute: AcademiaDirectoRoute,
  AcademiaExplorarRoute: AcademiaExplorarRoute,
  AcademiaRecursosRoute: AcademiaRecursosRoute,
  AcademiaIndexRoute: AcademiaIndexRoute,
  AcademiaCursoCourseIdRoute: AcademiaCursoCourseIdRoute,
  AcademiaLeccionCourseIdLessonIdRoute: AcademiaLeccionCourseIdLessonIdRoute,
}

const AcademiaRouteWithChildren = AcademiaRoute._addFileChildren(
  AcademiaRouteChildren,
)

interface FormulariosRouteChildren {
  FormulariosNuevaRoute: typeof FormulariosNuevaRoute
  FormulariosIndexRoute: typeof FormulariosIndexRoute
}

const FormulariosRouteChildren: FormulariosRouteChildren = {
  FormulariosNuevaRoute: FormulariosNuevaRoute,
  FormulariosIndexRoute: FormulariosIndexRoute,
}

const FormulariosRouteWithChildren = FormulariosRoute._addFileChildren(
  FormulariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRouteWithChildren,
  ActivarCuentaRoute: ActivarCuentaRoute,
  AjustesRoute: AjustesRoute,
  CalendarioRoute: CalendarioRoute,
  FormulariosRoute: FormulariosRouteWithChildren,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
  RecursosRoute: RecursosRoute,
  PortalFormularioRoute: PortalFormularioRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  PortalPlanRoute: PortalPlanRoute,
  PortalRecursosClinicosRoute: PortalRecursosClinicosRoute,
  PortalSuscripcionesRoute: PortalSuscripcionesRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
